### ISSUE TITLE
MAJ YT

### ISSUE THREAD

**Issue by dasga** [Korbak/RSSTube#3]
Salut Korbak =)
D’abord, merci pour cet addon !
Ensuite, la dernière MAJ de l'interface de YT semble avoir cassé ton bouton.
Tu pourrais jeter un oeil ?
(c'était pour m'abonner à "C'est ça l'histoire" ^^ )

**Comment by Korbak** [comment]
Salut :) !
Je viens seulement de voir l'issue, et j'ai pu le constater hier...

Il va falloir que je bosse sur un dév pour que la prochaine version s'affichant sur les 2 versions du site, car ça se base sur des facteurs que je n'ai pas.

Par exemple, chez moi, sur mon navigateur bourré de plugins qui ment sur mon identité sans complexes, j'ai toujours la même version de YouTube. Mais si je l'ouvre sans plugins, j'ai la nouvelle. Il me semble qu'à mon taf, c'est aussi l'ancienne version.

Donc en attendant que ce soit juste déployé une fois pour toutes, je vais bosser sur l'intégration des deux possibilités.

Merci du signalement en tout cas :) !

**Comment by Korbak** [comment]
V2.0 poussée à l'instant dans le store Mozilla : désormais compatible avec la nouvelle interface de YouTube (tout en le restant avec l'ancienne, alors ça fait du code un peu cracra) ;).

**Comment by dasga** [comment]
Je ré-ouvre pour la forme par ce qu'en vrai, c'est toujours cassé ^^

**Comment by Korbak** [comment]
Oui, je suis au courant. Malheureusement, je n'arrive pas à tester (j'ai encore l'ancienne version de YouTube qui s'affiche sur ma machine) :(.
Je manque de temps en ce moment pour m'y pencher plus en profondeur… mais je n'oublie pas qu'il faut que je m'en occupe !

**Comment by Korbak** [comment]
OK, je viens d'enfin merge un correctif (YES !). J'envoie ça rapidement sur le store de Firefox !
En tout cas, chez moi, ça a l'air de rouler :+1: !

![Capture d'écran test](https://user-images.githubusercontent.com/26529515/34130442-1c18029a-e448-11e7-9383-d51642ff6bb5.png)

**Comment by Lamecarlate** [comment]
Hellow,

je me vois contrainte de demander la réouverture de cet unique bug : YT a dû rechanger encore, chez moi ça marche pu. Je ne vois plus le bouton orange "Voir le flux". 

J'ai la version 2.1 de RSSTube (ainsi qu'elle est nommée sur le site des Addons Firefox), datant du 19 décembre, donc la plus récente si j'en crois les dates des fichiers ici.

Est-ce que tu reproduis le souci ?

**Comment by Korbak** [comment]
Hello,

Je ne parvenais pas à résoudre le problème, et au final, c'est la presse spécialisée qui a pointé le problème du doigt. Le fameux code adapté à Chrome et pas à Firefox qui ralentit YouTube a aussi impliqué des modifications de code rendant RSSTube inopérante.

J'ai ajouté le nécessaire dans le README : il faut faire un combo YouTube Classic + RSSTube pour que ça fonctionne à nouveau. Je n'ai pas trouvé mieux pour le moment :(.
