### ISSUE TITLE
Bouton invisible ?

### ISSUE THREAD

**Issue by mouarfff** [Korbak/RSSTube#7]
Bonjour !

Je suis contente que ce genre d'extenstio existe , cependant, je ne vois pas le bouton apparaitre sur la page ou danbs la barre d'outile ?

je suis sur firefox 61.0.1 sur windows 10 en 64bits, j'ai deja d'autres extensions isnatllées pour youtube mais comme c'est a priori juste un bvouton d'ajouté je me dis que ca doit pas etre bloquant ?

**Comment by Korbak** [comment]
J'ai pu constater que les modifications apportées à YouTube par Google empêchaient le fonctionnement de l'extension. Elle est désormais inutilisable sans addon comme "Youtube Classic" qui permet au code d'être parsé correctement et donc au bouton d'apparaître et de fonctionner. Les liens utiles et cette info sont ajoutés dans le README du projet. Désolé pour cette complication :(.
